#
# Executes commands at logout.
#
# Authors:
#   Ratheesh <ratheeshreddy@gmail.com
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

# vim: set ft=zsh ff=unix ts=4 sw=4 tw=0 expandtab:
# End of File
