#
# User configuration sourced by login shells
#

# Initialize zim
# [[ -s ${ZIM_HOME}/login_init.zsh ]] && source ${ZIM_HOME}/login_init.zsh

# ===== Customization =====
(
  local dir file
  setopt LOCAL_OPTIONS EXTENDED_GLOB
  autoload -U zrecompile

  zim_mods=${ZDOTDIR:-${HOME}}/.zim/modules
  setopt EXTENDED_GLOB

  # zcompile the completion cache; siginificant speedup.
  for file in ${ZDOTDIR:-${HOME}}/.zcomp^(*.zwc)(.); do
    zrecompile -pq ${file}
  done

  # from prezto
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
      zrecompile -pq "$zcompdump"
  fi

  # zcompile .zshrc
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zshrc

  # zcompile enabled module init scripts
  for file in ${ZIM_HOME}/modules/${^zmodules}/init.zsh(-.N); do
    zrecompile -pq ${file}
  done

  # zcompile all prompt setup scripts
  for file in ${ZIM_HOME}/modules/prompt/functions/prompt_*_setup; do
    zrecompile -pq ${file}
  done

  # zcompile all .zsh files in the custom module
  for file in ${zim_mods}/custom/**/^(README.md|*.zwc)(.); do
    zrecompile -pq ${file}
  done

  # zcompile all autoloaded functions
  for file in ${zim_mods}/**/functions/^(*.zwc)(.); do
    zrecompile -pq ${file}
  done

  # syntax-highlighting
  for file in ${zim_mods}/syntax-highlighting/external/highlighters/**/*.zsh; do
    zrecompile -pq ${file}
  done
  zrecompile -pq ${zim_mods}/syntax-highlighting/external/zsh-syntax-highlighting.zsh

  # zsh-histery-substring-search
  zrecompile -pq ${zim_mods}/history-substring-search/external/zsh-history-substring-search.zsh

  # zsh-histery-substring-search
  zrecompile -pq ${zim_mods}/vimode/external/zsh-vimode-visual.zsh

  # zsh-autosuggestions.zsh
  zrecompile -pq ${zim_mods}/autosuggestions/external/zsh-autosuggestions.zsh

  # forgit
  zrecompile -pq ${zim_mods}/forgit/external/forgit.plugin.zsh

  # Extra additions

  # other rc files as well
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zimrc
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zshenv
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zprofile
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zlogin

  # get fzf init script compiled
  [ -f ~/.fzf.zsh ] && zrecompile -pq ~/.fzf.zsh

) &!

# Print a random, hopefully interesting, adage.
# if (( $+commands[fortune] )); then
#  if [[ -t 0 || -t 1 ]]; then
# 	if (( $+commands[lolcat] ));then
# 		fortune -a de | cowsay -f tux | lolcat
# 	else
# 		fortune -a de | cowsay -f tux
# 	fi
#    print
#  fi
# fi

# vim: set ft=zsh ff=unix ts=4 sw=4 tw=0 expandtab:
# End of File
